services:
  - type: web
    name: job-portal
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: job-portal-db
          property: connectionString
    autoDeploy: false

databases:
  - name: job-portal-db
    databaseName: jobportal
    user: jobportal
    plan: free